name: Auto Build

on:
  repository_dispatch:
    types:
      - Auto-build

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-18.06-k5.4
  CONFIG_FILE: config/immortalwrt-18.06-k5.4/config
  DIY1_SH: config/immortalwrt-18.06-k5.4/diy1.sh
  DIY2_SH: config/immortalwrt-18.06-k5.4/diy2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check server information
      run: |
        echo -e "ğŸ’¬ Server information \n"
        echo -e "ğŸ’» Server running on Ubuntu: [ Release: $(cat /etc/os-release | grep VERSION_CODENAME | cut -d '=' -f2) / Host: $(arch) ] \n"
        echo -e "ğŸ§® Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo -e "ğŸ’¾ Server memory usage: \n$(free -h) \n"
        echo -e "ğŸ—ƒï¸ Server space usag: \n$(df -hT ${GITHUB_WORKSPACE}) \n"

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android /etc/mysql /etc/php 2>/dev/null
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap* aspnetcore* || true
        sudo -E apt-get -y update
        sudo -E apt-get -qq install $(cat depends)
        sudo -E systemctl daemon-reload
        #sudo -E apt-get -y full-upgrade
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo timedatectl set-timezone "$TZ"
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt --single-branch --depth=1
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        chmod +x $DIY1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY1_SH

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -d files ] && mv -f files openwrt/files
        [ -e $CONFIG_FILE ] && mv -f $CONFIG_FILE openwrt/.config
        chmod +x $DIY2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY2_SH
        echo "COMPILE_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Clear server space
      id: clean
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        # Clean up server space
        cd openwrt/
        mkdir output
        cp -f bin/targets/*/*/*rootfs.tar.gz output/
        cp -f .config output/config
        rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null

        # Set output information
        df -hT ${PWD}
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Package Armvirt as OpenWrt
      uses: ffuqiangg/openwrt_packit@master
      env:
        SCRIPT_REPO_URL: https://github.com/ffuqiangg/openwrt_packit
        OPENWRT_ARMVIRT: openwrt/output/*rootfs.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_REPO_URL: ffuqiangg/amlogic-s9xxx-armbian
        KERNEL_VERSION_NAME: ${{ github.event.client_payload.kernel_name }}
        KERNEL_AUTO_LATEST: ${{ github.event.client_payload.kernel_auto }}
        GZIP_IMGS: .gz
        SCRIPT_S905D: mk_immortalwrt_18.06_k5.4_n1.sh
        OPENWRT_VER: ${{ env.COMPILE_DATE }}
        SFE_FLOW: 0
        ENABLE_WIFI_K504: 0
        ENABLE_WIFI_K510: 0
        DISTRIB_REVISION: ${{ env.COMPILE_DATE }}
        DISTRIB_DESCRIPTION: Immortalwrt
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Organize output file
      if: env.PACKAGED_STATUS == 'success'
      run: |
        cp -f openwrt/output/config ${{ env.PACKAGED_OYTPUTPATH }}/
        cd ${{ env.PACKAGED_OYTPUTPATH }} 
        sha256sum config > config.sha

    - name: Generate release tag
      id: tag
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "release_tag=immortalwrt-18.06-k5.4-$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
        cat > release.txt <<EOF
        ![immortalwrt 18.06 k5.4](https://img.shields.io/badge/immortalwrt-18.06_k5.4-informational?style=flat) [![Telegram](https://img.shields.io/badge/-Telegram-413f42?style=flat&logo=telegram&logoColor=white)](https://t.me/ffuqiangg)  [![Gmail](https://img.shields.io/badge/-Gmail-red?style=flat&logo=gmail&logoColor=white)](mailto:ffuqiangg@gmail.com)  [![Docker](https://img.shields.io/badge/-Docker-informational?style=flat&logo=docker&logoColor=white)](https://hub.docker.com/u/ffuqiangg)
        - é»˜è®¤IPï¼š192.168.1.99  å¯†ç ï¼špassword
        - æºç æ¥è‡ª [Immortalwrt-18.06-k5.4](https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06-k5.4)ï¼Œå›ºä»¶åªé€‚é… æ–è®¯N1ï¼Œæ‰“åŒ…è„šæœ¬åŸºäº [unifreq/openwrt_packit](https://github.com/unifreq/openwrt_packit) ä¿®æ”¹
        - å†…æ ¸æ¥è‡ªä»“åº“ [ffuqiangg/amlogic-s9xxx-armbian](https://github.com/ffuqiangg/amlogic-s9xxx-armbian)
        - ä¸»è¦æ’ä»¶ï¼šPasswall, OpenClash, Dockerman, docker-compose, FileBrowser, Samba4, FTP, Frpc, HD-idle, KMS
        EOF
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: ncipollo/release-action@main
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag: ${{ steps.tag.outputs.release_tag }}
        bodyFile: release.txt
        artifacts: |
          ${{ env.PACKAGED_OUTPUTPATH }}/*

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: codesnas/delete-older-releases@main
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 50
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Telegram notification
      run: |
        COMPILE_DATE_VAL=$(echo ${{ steps.tag.outputs.release_tag }} | rev | cut -d - -f -2 | rev)
        MSG="
        âœ… *immortalwrt-18.06-k5.4 ${{ env.COMPILE_DATE }}*
        
        ğŸ”˜ *åŸºæœ¬ä¿¡æ¯*
        ç¼–è¯‘æ—¶é—´ï¼š ${COMPILE_DATE_VAL:0:13}:${COMPILE_DATE_VAL:13}
        ç®¡ç†åå°ï¼š 192.168.1.99
        é»˜è®¤å¯†ç ï¼š password
        ä¸‹è½½åœ°å€ï¼š [release](https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ steps.tag.outputs.release_tag }})

        ğŸ’¬ \[ [Telegram](https://t.me/ffuqiangg) ]  \[ [Github](https://github.com/ffuqiangg) ]  \[ [Docker](https://hub.docker.com/u/ffuqiangg) ]
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}&parse_mode=MarkDown&disable_web_page_preview=true"
