name: Build Openwrt

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: true
        default: "immortalwrt-master"
        type: choice
        options:
          - lede
          - immortalwrt-18.06-k5.4
          - immortalwrt-master

env:
  FEEDS_CONF: config/${{ inputs.source_branch }}/feeds.conf.default
  CONFIG_FILE: config/${{ inputs.source_branch }}/config
  DIY1_SH: config/${{ inputs.source_branch }}/diy1.sh
  DIY2_SH: config/${{ inputs.source_branch }}/diy2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check server information
      run: |
        echo -e "üí¨ Server information \n"
        echo -e "üíª Server running on Ubuntu: [ Release: $(cat /etc/os-release | grep VERSION_CODENAME | cut -d '=' -f2) / Host: $(arch) ] \n"
        echo -e "üßÆ Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo -e "üíæ Server memory usage: \n$(free -h) \n"
        echo -e "üóÉÔ∏è Server space usag: \n$(df -hT ${GITHUB_WORKSPACE}) \n"

    - name: Initialization environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
        sudo -E apt-get -y update
        sudo -E apt-get -y purge azure-cli* ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -qq install $(cat depends)
        sudo -E systemctl daemon-reload
        #sudo -E apt-get -y full-upgrade
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo mkdir -p /workdir
        sudo chown ${USER}:${GROUPS} /workdir
        sudo timedatectl set-timezone "$TZ"
        echo "status-success" >> ${GITHUB_OUTPUT}

    - name: Clone source code [ ${{ inputs.source_branch }} ]
      id: codes
      working-directory: /workdir
      if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
      run: |
        # Set up compilation source code
        elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
            REPO_URL="https://github.com/coolsnowwolf/lede"
            REPO_BRANCH="master"
            echo "package_repo=ffuiangg" >> ${GITHUB_OUTPUT}
            echo "make_sh=mk_lede_n1.sh" >> ${GITHUB_OUTPUT}
        elif [[ "${{ inputs.source_branch }}" == "immortalwrt-master"* ]]; then
            REPO_URL="https://github.com/immortalwrt/immortalwrt"
            REPO_BRANCH="master"
            echo "package_repo=ophub" >> ${GITHUB_OUTPUT}
        elif [[ "${{ inputs.source_branch }}" == *"immortalwrt-18.06-k5.4"* ]]; then
            REPO_URL="https://github.com/immortalwrt/immortalwrt"
            REPO_BRANCH="openwrt-18.06-k5.4"
            echo "package_repo=ffuqiangg" >> ${GITHUB_OUTPUT}
            echo "make_sh=mk_immortalwrt_18.06_k5.4_n1.sh" >> ${GITHUB_OUTPUT}
        fi

        # Clone source code
        git clone -q --single-branch --depth=1 -b ${REPO_BRANCH} ${REPO_URL} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

        # Set output information
        echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]"
        df -hT ${PWD}
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Load custom feeds
      run: |
        [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
        chmod +x ${DIY1_SH}
        cd openwrt/
        ${GITHUB_WORKSPACE}/${DIY1_SH}

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -d files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && cp -f $CONFIG_FILE openwrt/.config
        chmod +x ${DIY2_SH}
        cd openwrt
        ${GITHUB_WORKSPACE}/${DIY2_SH}
        echo "COMPILE_DATE=$(date +%Y%m%d)" >> ${GITHUB_ENV}

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(($(nproc) +1 )) V=s || make -j1 || make -j1 V=s
        echo "status=success" >> ${GITHUB_OUTPUT}
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> ${GITHUB_ENV}

    - name: Clear server space
      id: clean
      if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
      run: |
        # Clean up server space
        cd openwrt/
        mkdir output
        cp -f bin/targets/*/*/*rootfs.tar.gz output/
        cp -f .config output/config
        rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null

        # Set output information
        df -hT ${PWD}
        echo "build_tag=${{ inputs.source_branch }}_$(date +"%Y.%m.%d-%H%M")" >> ${GITHUB_OUTPUT}
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Upload OpenWrt to Release
      uses: ncipollo/release-action@main
      if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
      with:
        tag: ${{ steps.clean.outputs.build_tag }}
        artifacts: openwrt/output/*
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: true
        token: ${{ secrets.GH_TOKEN }}

    - name: Package Openwrt [ ophub ]
      if: ${{ steps.clean.outputs.status }} == 'success' && ${{ steps.codes.outputs.package_repo }} == 'ophub' && !cancelled()
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/bin/targets/*/*/*.tar.gz
        openwrt_board: s905d
        kernel_repo: ophub/kernel
        openwrt_kernel: 5.15.1_6.1.1
        kernel_usage: flippy
        auto_kernel: auto
        openwrt_size: 720
        gh_token: ${{ secrets.GH_TOKEN }}

    - name: Package Openwrt [ ffuqiangg ]
      if: ${{ steps.clean.outputs.status }} == 'success' && ${{ steps.codes.outputs.package_repo }} == 'ffuqiangg' && !cancelled()
      uses: ffuqiangg/openwrt_packit@master
      env:
        SCRIPT_REPO_URL: https://github.com/ffuqiangg/openwrt_packit
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_REPO_URL: ffuqiangg/amlogic-s9xxx-armbian
        KERNEL_VERSION_NAME: 5.4.1
        KERNEL_AUTO_LATEST: auto
        GZIP_IMGS: .7z
        SCRIPT_S905D: ${{ steps.codes.outputs.make_sh }}
        OPENWRT_VER: R${{ env.COMPILE_DATE }}
        SFE_FLOW: 0
        ENABLE_WIFI_K504: 0
        ENABLE_WIFI_K510: 0
        DISTRIB_REVISION: R${{ env.COMPILE_DATE }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Package Openwrt [ ffuqiangg ]
      if: ${{ inputs.source_branch }} == 'lede' && !cancelled()
      uses: ffuqiangg/openwrt_packit@master
      env:
        SCRIPT_REPO_URL: https://github.com/ffuqiangg/openwrt_packit
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_REPO_URL: breakings/Openwrt
        KERNEL_VERSION_NAME: 5.10.1_5.15.1_6.1.1
        KERNEL_AUTO_LATEST: auto
        GZIP_IMGS: .7z
        SCRIPT_S905D: ${{ steps.codes.outputs.make_sh }}
        OPENWRT_VER: R${{ env.COMPILE_DATE }}
        SFE_FLOW: 0
        ENABLE_WIFI_K504: 0
        ENABLE_WIFI_K510: 0
        DISTRIB_REVISION: R${{ env.COMPILE_DATE }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload firmware to release
      uses: ncipollo/release-action@main
      if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag: ${{ steps.clean.outputs.build_tag }}
        artifacts: |
          ${{ env.PACKAGED_OUTPUTPATH }}/*.img.gz
          ${{ env.PACKAGED_OUTPUTPATH }}/*.7z
        body: |
          ### OpenWrt Image information
          - Default IP: 192.168.1.1
          - Default username: root
          - Default password: password
          - Default WIFI name: OpenWrt
          - Default WIFI password: none

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: codesnas/delete-older-releases@main
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 50
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Telegram notification
      run: |
        COMPILE_DATE_VAL=$(echo ${{ steps.tag.outputs.release_tag }} | cut -d - -f 2-)
        MSG="
        ‚úÖ *${{ inputs.souce_branch }} ${{ env.COMPILE_DATE }}*
        
        üîò *Âü∫Êú¨‰ø°ÊÅØ*
        ÁºñËØëÊó∂Èó¥Ôºö ${COMPILE_DATE_VAL:0:13}:${COMPILE_DATE_VAL:13}
        ÁÆ°ÁêÜÂêéÂè∞Ôºö 192.168.1.99
        ÈªòËÆ§ÂØÜÁ†ÅÔºö password
        ‰∏ãËΩΩÂú∞ÂùÄÔºö [release](https://github.com/ffuqiangg/build_openwrt/releases/tag/${{ steps.clean.outputs.build_tag }}

        üí¨ \[ [Telegram](https://t.me/ffuqiangg) ]  \[ [Github](https://github.com/ffuqiangg) ]  \[ [Docker](https://hub.docker.com/u/ffuqiangg) ]
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}&parse_mode=MarkDown&disable_web_page_preview=true"
